module.exports = {
	BaseRepository: require('./baseRepository'),
	usersRepository: require('./usersRepository'),
	rolesRepository: require('./rolesRepository'),
	parentsRepository: require('./parentsRepository'),
	driversRepository: require('./driversRepository'),
	studentsRepository: require('./studentsRepository'),
	busesRepository: require('./busesRepository'),
	routesRepository: require('./routesRepository'),
	stopsRepository: require('./stopsRepository'),
	tripsRepository: require('./tripsRepository'),
	tripStopsRepository: require('./tripStopsRepository'),
	tripPassengersRepository: require('./tripPassengersRepository'),
	pickupRecordsRepository: require('./pickupRecordsRepository'),
	navigationLogsRepository: require('./navigationLogsRepository'),
	messagesRepository: require('./messagesRepository'),
	notificationsRepository: require('./notificationsRepository'),
	userNotificationsRepository: require('./userNotificationsRepository'),
};