const BUS_STATUSES = ['ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE'];
const RELATIONSHIPS = ['PARENT', 'GUARDIAN', 'RELATIVE'];
const GENDER = ['MALE', 'FEMALE', 'OTHER'];
const TRIP_STATUSES = ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
const SHIFT = ['MORNING', 'AFTERNOON'];
const PICKUP_STATUS = ['PICKED_UP', 'DROPPED_OFF', 'MISSED', 'WAITING'];
const NOTIFICATION_TYPES = ['INFO', 'SUCCESS', 'ALERT', 'REMINDER', 'WARNING', 'SYSTEM'];
const WEEKDAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
const TIME_PATTERN = /^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/; // HH:mm or HH:mm:ss

module.exports = {
	BUS_STATUSES,
	RELATIONSHIPS,
	GENDER,
	TRIP_STATUSES,
	SHIFT,
	PICKUP_STATUS,
	NOTIFICATION_TYPES,
	WEEKDAYS,
	TIME_PATTERN
};